<a href="https://colab.research.google.com/github/DeanAdrian/CpE-AIML/blob/main/laboratories/58090_Lab02_Jabolt/58090_Lab02_Jabolt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <div align="center">**Lab 02 - Linear Algebra Review**</div> 

| Submitted By:          | Instructor:               |
|------------------------|---------------------------|
| Baluyot, John Michael  | Engr. Dylan Josh D. Lopez |
| Barona, Federico III   |                           | 
| Estocapio, Dean Adrian |                           |
| Garcia, Lance Gabriel  |                           | 

In [ ]:
import numpy as np
import pandas as pd

### Case 2.a

>This given function uses a numpy function "np.linalg.norm" that gets the magnitude of the vector 

In [ ]:
def vector_magnitude_np(vector):
  magnitude = np.linalg.norm(vector)
  return magnitude

> Getting the vector magnitude without use of any numpy functions

>This given function shares the same function from the previous function without using any numpy function

>The logic behind the function itself, is it breaks down all the possible operation needed in order to evaluate the final answer or magnitude of the given vector

> the function also evaluates whether the given vector has 1 dimension or more before taking appropriate operation


In [ ]:
def  vector_magnitude(vector):
  magnitude = 0
  if vector.ndim == 1:
    for values in vector:
      values = values*values
      magnitude = magnitude + values
    magnitude = magnitude**(1/2)
  else:
    for values in vector:
      values = values@values
      magnitude = magnitude + values
    magnitude = magnitude**(1/2)
  return magnitude

##### Given:

In [ ]:
u = np.array([1,2,3])         # 1 dimensional vector
v = np.array([4,2,-3])
t = np.array([[1,2,3],        # 2 dimensional vector
              [1,2,3]])

##### Results

In [ ]:
vector_magnitude_np(u)

3.7416573867739413

In [ ]:
vector_magnitude_np(t) 

5.291502622129181

In [ ]:
vector_magnitude(u)

3.7416573867739413

In [ ]:
vector_magnitude(t)

5.291502622129181

### Case 4.c


Problem 4.c: Computational Programming (Also Laboratory 2)

Encode Equations 3.1 to 3.4 as the class LRegression wherein:

*   LRegression should be instantiated with a dataset $X$, a ground truth vector $y$, and a parameter vector $\theta$. Each parameter should have a data type of numpy.array.
*   It should further have methodsreflecting to at least the four (4) aforementioned equations. Each should have a return value.



In [ ]:
class LRegression():
  def __init__(self, dataSet, y_GndTruth, thetaVector):
    self.dataSet = dataSet
    self.y_GndTruth = y_GndTruth
    self.thetaVector = thetaVector

  def getVectorMagnitude(self):
    magnitude = np.linalg.norm(self.dataSet)
    return magnitude

  def getZ(self): ## Eq. 3.1
    self.dataSetT = self.dataSet.transpose()
    self.z = np.dot(self.dataSetT, self.thetaVector)
    return self.z 

  def getActivation (self): ## Eq. 3.2 & 3.3
    self.activation = 1/(1+np.exp(-self.z))
    return self.activation

  def getLoss(self): ## Eq. 3.4
    m = self.y_GndTruth.shape[0]
    yt = self.y_GndTruth.transpose()

    lossEq= (-1*yt)*(np.log(self.activation)) - ((1-self.y_GndTruth).transpose())*(np.log(1-self.activation))
    self.J = (1/m)*lossEq
    return self.J

##### Given:

In [ ]:
X = np.random.random((300,5))*100
theta = np.random.random((300,1))
y = np.random.randint(0,2,(300,1))

##### Results:

In [ ]:
Regression = LRegression(X, y, theta)

In [ ]:
Regression.getVectorMagnitude()

2241.764672613696

In [ ]:
Regression.getZ()

array([[7339.68140797],
       [7855.70038308],
       [6813.07696753],
       [7102.82485885],
       [7789.00840542]])

In [ ]:
Regression.getActivation()

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
Regression.getLoss()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in multiply


array([[inf, nan, inf, ..., nan, nan, nan],
       [inf, nan, inf, ..., nan, nan, nan],
       [inf, nan, inf, ..., nan, nan, nan],
       [inf, nan, inf, ..., nan, nan, nan],
       [inf, nan, inf, ..., nan, nan, nan]])